### ISSUE TITLE
Getting an Import error

### ISSUE THREAD

**Issue by Kodiakev** [TheresAFewConors/Sooty#109]
I know this might be a user error, but I'm getting this error whenever I try to run Sooty.py:

Traceback (most recent call last):
  File "Sooty.py", line 20, in <module>
    import strictyaml
  File "/usr/local/lib/python3.8/dist-packages/strictyaml/__init__.py", line 2, in <module>
    from strictyaml.parser import load
  File "/usr/local/lib/python3.8/dist-packages/strictyaml/parser.py", line 21, in <module>
    from ruamel.yaml.compat import PY2
ImportError: cannot import name 'PY2' from 'ruamel.yaml.compat' (/usr/local/lib/python3.8/dist-packages/ruamel/yaml/compat.py)

Any tips?

**Comment by Kodiakev** [comment]
Edit - had to install pip install 'ruamel.yaml<=0.15.94' and sudo apt install python3-tk
