### ISSUE TITLE
ModuleNotFoundError: No module named 'six.moves'

### ISSUE THREAD

**Issue by alex27riva** [TheresAFewConors/Sooty#110]
Hi everyone, I'm experiencing the following issue:

```
➜   python3 Sooty.py
Traceback (most recent call last):
  File "/home/user/Downloads/Sooty/Sooty.py", line 20, in <module>
    import strictyaml
  File "/home/user/Downloads/Sooty/venv/lib64/python3.12/site-packages/strictyaml/__init__.py", line 2, in <module>
    from strictyaml.parser import load
  File "/home/user/Downloads/Sooty/venv/lib64/python3.12/site-packages/strictyaml/parser.py", line 10, in <module>
    from strictyaml.any_validator import Any
  File "/home/user/Downloads/Sooty/venv/lib64/python3.12/site-packages/strictyaml/any_validator.py", line 2, in <module>
    from strictyaml.compound import FixedSeq, Map
  File "/home/user/Downloads/Sooty/venv/lib64/python3.12/site-packages/strictyaml/compound.py", line 5, in <module>
    from strictyaml.scalar import ScalarValidator, Str
  File "/home/user/Downloads/Sooty/venv/lib64/python3.12/site-packages/strictyaml/scalar.py", line 7, in <module>
    import dateutil.parser
  File "/home/user/Downloads/Sooty/venv/lib64/python3.12/site-packages/dateutil/parser/__init__.py", line 2, in <module>
    from ._parser import parse, parser, parserinfo, ParserError
  File "/home/user/Downloads/Sooty/venv/lib64/python3.12/site-packages/dateutil/parser/_parser.py", line 50, in <module>
    from .. import tz
  File "/home/user/Downloads/Sooty/venv/lib64/python3.12/site-packages/dateutil/__init__.py", line 16, in __getattr__
    return importlib.import_module("." + name, __name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Downloads/Sooty/venv/lib64/python3.12/site-packages/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/home/user/Downloads/Sooty/venv/lib64/python3.12/site-packages/dateutil/tz/tz.py", line 21, in <module>
    from six.moves import _thread
ModuleNotFoundError: No module named 'six.moves'

```
**What Operating System are you using?**

Fedora Linux 40 (Workstation Edition), Python 3.12

**Steps to reproduce**
 1. `git clone git@github.com:TheresAFewConors/Sooty.git`
 2. `cd Sooty`
 3. `python3 -m venv venv`
 4. `source venv/bin/activate`
 5. `pip3 install -r requirements.txt`
 6. `python3 Sooty.py`

How to fix this issue? Is this tool still maintained?

Bye

**Comment by TheresAFewConors** [comment]
looks like you're missing a library that the req file isn't handling. Run `pip3 install six` which should download the required lib.
