### ISSUE TITLE
the docker version seem not working. Error:  "ImportError: cannot import name 'PY2' from 'ruamel.yaml.compat'"

### ISSUE THREAD

**Issue by zebux** [TheresAFewConors/Sooty#111]
**Describe the bug**
After the command : 
  $ docker build -t sooty .
  $ docker run --rm -it sooty
I have the error message : 
Traceback (most recent call last):
  File "/app/Sooty.py", line 20, in <module>
    import strictyaml
  File "/usr/local/lib/python3.7/site-packages/strictyaml/__init__.py", line 2, in <module>
    from strictyaml.parser import load
  File "/usr/local/lib/python3.7/site-packages/strictyaml/parser.py", line 21, in <module>
    from ruamel.yaml.compat import PY2
ImportError: cannot import name 'PY2' from 'ruamel.yaml.compat' (/usr/local/lib/python3.7/site-packages/ruamel/yaml/compat.py)

**Reproduction Steps**
1. git clone https://github.com/TheresAFewConors/Sooty.git
2. docker build -t sooty . && docker run --rm -it sooty

**Expected behavior**
A clear and concise description of what was expected to happen.

**Screenshots**
![image](https://github.com/user-attachments/assets/b62d841d-bf21-41d1-bc9d-8c175c0e4298)

**Desktop Operating System:**
 - OS: 
 $ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04.1 LTS"
- Docker version
$ docker -v
Docker version 27.3.1, build ce12230

**Additional context**
I think the issue may be solve manualy (I am not a python / docker expert) if you downgrade the ruamel.yaml
$ docker run --rm -it sooty /bin/bash
root@c1c59e030321:/app#
root@c1c59e030321:/app# pip install 'ruamel.yaml<=0.15.94'
Collecting ruamel.yaml<=0.15.94
  Downloading ruamel.yaml-0.15.94-cp37-cp37m-manylinux1_x86_64.whl (647 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 647.9/647.9 kB 34.5 MB/s eta 0:00:00
Installing collected packages: ruamel.yaml
  Attempting uninstall: ruamel.yaml
    Found existing installation: ruamel.yaml 0.18.6
[...]
root@c1c59e030321:/app# python Sooty.py
Cant install Win32com package
Config.yaml not found. Check the example config file and rename to 'config.yaml'.

 @@@@@@    @@@@@@    @@@@@@   @@@@@@@  @@@ @@@
@@@@@@@   @@@@@@@@  @@@@@@@@  @@@@@@@  @@@ @@@
!@@       @@!  @@@  @@!  @@@    @@!    @@! !@@
!@!       !@!  @!@  !@!  @!@    !@!    !@! @!!
!!@@!!    @!@  !@!  @!@  !@!    @!!     !@!@!
 !!@!!!   !@!  !!!  !@!  !!!    !!!      @!!!
     !:!  !!:  !!!  !!:  !!!    !!:      !!:
    !:!   :!:  !:!  :!:  !:!    :!:      :!:
:::: ::   ::::: ::  ::::: ::     ::       ::
:: : :     : :  :    : :  :      :        :

                           by @TheresAFewConors

 The SOC Analyst's all-in-one tool to automate and speed up workflow

 Press Enter to continue..

I hope this may help

**Comment by zebux** [comment]
I try to change my requirement.txt file and add the line : 
ruamel.yaml==0.17.32

And it work as expected. The version 0.17.32 seem to be the last working package. A superior version of the package displays the error.

**Comment by ubahmapk** [comment]
I get the same results when not using the Dockerfile.

Adding the ruamel.yaml==0.17.32 to requirements.txt resolves the problem, but is there a better solution than pinning the version to an older release?
