### ISSUE TITLE
'configvars' undefined when not within docker container

### ISSUE THREAD

**Issue by basedfir** [TheresAFewConors/Sooty#84]
**Describe the bug**
Hi mate, this bug is only present when launching sooty with 'docker run --rm -it sooty'
I had no luck installing on Windows standalone due to some other issues but works fine in docker itself when interacting within the container using 'docker exec -it epic_brahmagupta /bin/bash', then 'python Sooty.py'

Not sure what the link is between interacting within the docker container and not, however this is the error message:

VirusTotal Report:
Traceback (most recent call last):
  File "/app/Sooty.py", line 1224, in <module>
    mainMenu()
  File "/app/Sooty.py", line 181, in mainMenu
    switchMenu(input())
  File "/app/Sooty.py", line 56, in switchMenu
    repChecker()
  File "/app/Sooty.py", line 393, in repChecker
    params = {'apikey': configvars.data['VT_API_KEY'], 'ip': wIP}
NameError: name 'configvars' is not defined

This appears to be there for all modules, so 'configvars' is suddenly undefined when using the 'docker run --rm -it sooty' command.

**Reproduction Steps**
1. Install with docker on windows using 1. 'docker build -t sooty', 2. 'docker run --rm -it sooty'
2. Attempt any url/ ip check
...

**Expected behavior**
This should work in the same way as interacting within the container - check successfully, due to undefined configvars when not within.

**Desktop Operating System:**
 -OS Win 10 x64
(MS Win 10 Pro - 10.0.19042 Build 19042)

**Additional context**

**Comment by TheresAFewConors** [comment]
Thanks for raising the issue - can you confirm if you have the Virus Total API key present in the config file? If the issue persists then it is a new one, otherwise its related to a different bug that is next in line to be done.

**Comment by basedfir** [comment]
Cheers for coming back to me. Yeah, so the VTtotal API key is present, the only ones that aren’t are phishtank (as they’ve suspended registration).

For whatever reason it says that the config.yaml isn’t found when interacting with the container, but of course is found when inside of the container.
