### ISSUE TITLE
Error with checking for Tor exit nodes

### ISSUE THREAD

**Issue by bigverm23** [TheresAFewConors/Sooty#98]
**Describe the bug**
 TOR Exit Node Report: 
There is an error with checking for Tor exit nodes:
local variable 'f' referenced before assignment

**Reproduction Steps**
1.  Sooty.py
2. OPTION 3
3. enter email address OR IP or URL & click Enter
...

**Expected behavior**
first time using it so I expect it would complete a check and progress.  iThis particular error was for an email address and it errored on the Tor exit node check.
I also checked an IP address with OPTION 3 and it errored on VirusTotal Report and hangs on Checking BadIP's (never progresses.

**Screenshots**
` TOR Exit Node Report: 
There is an error with checking for Tor exit nodes:
local variable 'f' referenced before assignment
VirusTotal Report:
error

 Checking BadIP's... 
Traceback (most recent call last):
  File "/home/USER/Sooty/Sooty.py", line 1231, in <module>
    mainMenu()
  File "/home/USER/Sooty/Sooty.py", line 191, in mainMenu
    switchMenu(input())
  File "/home/USER/Sooty/Sooty.py", line 57, in switchMenu
    repChecker()
  File "/home/USER/Sooty/Sooty.py", line 463, in repChecker
    f.write("\n\n ---------------------------------")
UnboundLocalError: local variable 'f' referenced before assignment
`

**Desktop Operating System:**
 Ubuntu 22.04 LTS

**Comment by jrmain** [comment]
Same problem here. Ubuntu 18.04. Can the Tor check be disabled?
